Add uk lang сompatibility with version 1.8
bambulab/BambuStudio pull request #2913
Opened 2023-11-17 14:30 UTC by iZonex

Introducing Ukrainian Language Support for Version 1.8

<img width="596" alt="Screenshot 2023-11-17 at 17 37 59" src="https://github.com/bambulab/BambuStudio/assets/2759749/d28123e9-a721-46a3-a9d1-dd84909ef450">
<img width="1512" alt="Screenshot 2023-11-17 at 17 12 26" src="https://github.com/bambulab/BambuStudio/assets/2759749/320a7525-89ec-4586-bf66-be8af2d69eff">

### Changes Description:
- Implemented complete interface localization in Ukrainian.
- Ensured compatibility with the new version 1.8, including interface updates and enhanced functionalities.
- Modified `resources/web/data/text.js` for textual changes in the interface.
- Updated and added localization files `BambuStudio_uk.po` and `.mo` to support the Ukrainian language.

### Purpose of Changes:
The purpose of these changes is to extend the application's accessibility to Ukrainian-speaking users and update compatibility with the latest software version, thereby improving overall performance and user experience.

2023-11-21 16:18 UTC, kiddden approved these changes
the localization seems to be clear and correct

2023-11-21 20:16 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Друкувати пластину"
Друкувати стіл

2023-11-21 20:25 UTC, man55 requested changes
грац

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Назва пластини"
Назва столу

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Bambu Cool Пластина"
Cool Plate

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "PLA Пластина"
PLA Plate

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Bamabu Engineering Пластина"
Engineering Plate

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Bamabu Smooth PEI Пластина"
Smooth PEI Plate

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "High temperature Пластина"
High temperature Plate

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Bamabu Textured PEI Пластина"
Textured PEI Plate

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +"Увага! Калібрування потоку на текстурованій PEI-пластини може не вдалося через "
Увага! Калібрування потоку на текстурованій PEI-пластині може не вдастися через

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Cool Пластина / PLA Пластина"
Cool Plate / PLA Plate

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Engineering Пластина"
Engineering Plate

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Smooth PEI Пластина / High Temp Пластина"
Smooth PEI Plate / High Temp Plate

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Textured PEI Пластина"
Textured PEI Plate

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +"охолодження першого шару був закритий, щоб покращити адгезіюРобочої пластини"
охолодження першого шару був закритий, щоб покращити адгезію Робочої пластини

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Мости без опор"
Мости без підтримок

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
>  "Розділіть свої друки на пластини\n"
Розділіть свої друки на столи\n

2023-11-21 20:25 UTC, man55 commented on bbl/i18n/uk/BambuStudio_uk.po
> +"окремі пластини, готові до друку? Це спростить процес відстеження всіх частин."
окремі столи, готові до друку? Це спростить процес відстеження всіх частин.

2023-11-21 21:26 UTC, iZonex commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "PLA Пластина"
Please learn English

2023-11-21 21:26 UTC, iZonex commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Bamabu Engineering Пластина"
Please learn English

2023-11-21 21:26 UTC, iZonex commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Bamabu Smooth PEI Пластина"
Please learn English

2023-11-21 21:27 UTC, iZonex commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Textured PEI Пластина"
Please learn English

2023-11-21 22:55 UTC, iZonex commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Друкувати пластину"
Стіл == Table!

2023-11-21 22:56 UTC, iZonex commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Назва пластини"
Plate != стол, Plate == пластина

2023-11-21 22:58 UTC, iZonex commented on bbl/i18n/uk/BambuStudio_uk.po
> +msgstr "Мости без опор"
Please, use to speak international language. "Мости без опор" almost same as "Мости без підтримок"

2023-11-21 22:58 UTC, iZonex commented on bbl/i18n/uk/BambuStudio_uk.po
> +"окремі пластини, готові до друку? Це спростить процес відстеження всіх частин."
same meaning

2023-11-21 23:00 UTC, iZonex commented on bbl/i18n/uk/BambuStudio_uk.po
>  "Розділіть свої друки на пластини\n"
Plate != Table

2023-11-21 23:04 UTC, iZonex commented on bbl/i18n/uk/BambuStudio_uk.po
> +"охолодження першого шару був закритий, щоб покращити адгезіюРобочої пластини"
Fixed thanks!

2023-11-21 23:47 UTC, iZonex commented
@lanewei120 Can you please review and merge before release 1.8. We with our Ukraine community did to much improvements for better translation.

2023-11-22 00:25 UTC, lanewei120 commented
@iZonex 

thanks for doing this
I have just synced the codes of master to newest
could you rebase to the master, and submit it again

we will merge as soon as you finish

2023-11-22 08:59 UTC, lanewei120 commented
@iZonex 
is it ready now?

2023-11-22 09:00 UTC, man55 approved these changes

2023-11-22 09:02 UTC, iZonex commented
> @iZonex is it ready now?

Yes! 

**msgid "Delete Preset"**
msgstr ""

msgid "Are you sure to delete the selected preset?"
msgstr ""

**msgid "Delete preset"**
msgstr ""

2023-11-22 09:22 UTC, lanewei120 commented
> > @iZonex is it ready now?
> 
> @lanewei120 Yes!
> 
> Please take a look on translations around code base with "Delete Presets" is duplicated is ok, but I think Delete **P**resets and Delete **p**resets is can be duplicate by typo
> 
> **msgid "Delete Preset"** msgstr ""
> 
> msgid "Are you sure to delete the selected preset?" msgstr ""
> 
> **msgid "Delete preset"** msgstr ""

that is ok currently
thanks for doing this

2023-11-22 09:25 UTC, lanewei120 commented
![image](https://github.com/bambulab/BambuStudio/assets/106916061/3a729db9-c22d-45a3-82ad-b9359ac092fc)

2023-11-22 09:26 UTC, lanewei120 commented
seems can not rebase
please rebase it manually and submit again

@iZonex

2023-11-22 09:45 UTC, iZonex commented
> seems can not rebase please rebase it manually and submit again
> 
> @iZonex

Rebased to one commit for top.

2023-11-22 09:46 UTC, merged